name: Symfony Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      # Set up PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: mbstring, intl, pdo, pdo_mysql
          tools: composer

      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up environment variables
      - name: Set environment file
        run: |
          php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"

      # Cache Composer dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-php-

      # Install dependencies
      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        continue-on-error: true

      # Update dependencies if installation fails
      - name: Update dependencies (if needed)
        if: failure()
        run: composer update --no-ansi --no-interaction --no-progress

      # Run Symfony tests
      - name: Run tests
        run: ./bin/phpunit
